/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteMenuRouteImport } from './routes/_site.menu'
import { Route as SiteGalerieRouteImport } from './routes/_site.galerie'
import { Route as SiteContactRouteImport } from './routes/_site.contact'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalerieRoute = SiteGalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/contact': typeof SiteContactRoute
  '/galerie': typeof SiteGalerieRoute
  '/menu': typeof SiteMenuRoute
}
export interface FileRoutesByTo {
  '/contact': typeof SiteContactRoute
  '/galerie': typeof SiteGalerieRoute
  '/menu': typeof SiteMenuRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/galerie': typeof SiteGalerieRoute
  '/_site/menu': typeof SiteMenuRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/galerie' | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/galerie' | '/menu' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/contact'
    | '/_site/galerie'
    | '/_site/menu'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/menu': {
      id: '/_site/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof SiteMenuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/galerie': {
      id: '/_site/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof SiteGalerieRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteGalerieRoute: typeof SiteGalerieRoute
  SiteMenuRoute: typeof SiteMenuRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteGalerieRoute: SiteGalerieRoute,
  SiteMenuRoute: SiteMenuRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
